### ISSUE TITLE
Disable alerts

### ISSUE THREAD

**Issue by ian-Tr** [InfiniteLoopAlchemist/CritMatic#1]
Hey, just wanted to say thanks for making CritMatic! It's a fun idea and it works well! 

I just wish there was an option to turn off the raid-warning style alerts when a new record happens, and just keep the tooltip records. I enjoy tracking the highest hits of my abilities, however, the alerts can sometimes feel a bit distracting... especially while raiding or playing hardcore because focusing is more sensitive. I think it would be a nice option to have, or at least add a "muted"/"none" sound option. I also noticed that CritMatic info doesn't show in macro tooltips (when using #showtooltip in the macro). Not sure if that's feasible to do or not.

Cheers!

**Comment by InfiniteLoopAlchemist** [comment]
Hey sorry for the late reply but the next update or two will have this. But you can try setting the font and sound to none. That should stop displaying the alerts but keep the data logged.

**Comment by InfiniteLoopAlchemist** [comment]
> Hey, just wanted to say thanks for making CritMatic! It's a fun idea and it works well!
> 
> I just wish there was an option to turn off the raid-warning style alerts when a new record happens, and just keep the tooltip records. I enjoy tracking the highest hits of my abilities, however, the alerts can sometimes feel a bit distracting... especially while raiding or playing hardcore because focusing is more sensitive. I think it would be a nice option to have, or at least add a "muted"/"none" sound option. I also noticed that CritMatic info doesn't show in macro tooltips (when using #showtooltip in the macro). Not sure if that's feasible to do or not.
> 
> Cheers!

I added options to disable chat / alets notifications and a new option too disable all sounds. have a great day.
